### PR TITLE
[UPDATE] Adding code to store logs

### PR DESCRIPTION
**Pull request by vinnyfs89**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] **I have read CONTRIBUTING.md**
- [ ] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [ ] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [ ] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by utdrmac** [comment]
Shouldn't the logs be printed to stdout/stderr so that they are captured, and logged, and rotated by journalctl?

**Comment by vinnyfs89** [comment]
I just add another way to do this.

**Comment by utdrmac** [comment]
But then doesn't this break established functionality provided by the OS to do exactly what you want? Seems like re-inventing the wheel. You already have a mechanism for storing, accessing and rotating the logs, journalctl. or am I missing something more?

**Comment by vinnyfs89** [comment]
In fact, I disagree with your point of view. For my scenario, although you do not agree, as the python script is initialized as a service in background mode, no information about the script will be displayed, so for my scenario storing the logs becomes something useful. I do not see how "Reinventing the wheel" ...

But it's just my point of view that will probably help other people, but you can deny the pull request if you want.

**Comment by rnevet** [comment]
@utdrmac can you maybe clarify how should you use journalctl to view the bots log in the service scenario? (I have to admit Unix isn't my domain) maybe add that to the docs?

**Comment by utdrmac** [comment]
Since systemd became process 1 in all major linux operating systems, things like auto-restarting crashed applications, handling logs, rotating logs, etc, all of that is built-in to systemd. You simply launch your application and systemd does the rest. You don't need to code in external logging logic. Just print everything to stdout and systemd captures it all automatically and sends it to journald. You can view the logs like `journalctl -u lendingbot`

**Comment by utdrmac** [comment]
vinnfs's patch is essentially redirecting stdout and stderr away from systemd capture, and sending to a separate file. It's a simple solution to have ONLY the lendingbot logs in a separate file. You can get the same exact info by letting systemd handle it and use the journactl command to view the logs, albeit learning how to properly use journalctl.

**Comment by rnevet** [comment]
Thanks @utdrmac!

**Pull request closed without merging**
